//Ron Swanson quotes
const quotes = [
  { text: 'Crying: acceptable at funerals and the Grand Canyon.' },
  { text: 'I call this turf ‘n’ turf. It\'s a 16 oz T-bone and a 24 oz porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American.' },
  { text: 'Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.' },
  { text: 'Never half-ass two things. Whole-ass one thing.' },
  { text: '[On bowling] Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating.' },
  { text: 'Fishing relaxes me. It\'s like yoga, except I still get to kill something.' },
  { text: 'Just give me all the bacon and eggs you have. Wait...wait. I worry what you just heard was: Give me a lot of bacon and eggs. What I said was: Give me ALL the bacon and eggs you have. Do you understand?' },
  { text: 'When people get a little too chummy with me I like to call them by the wrong name to let them know I don\'t really care about them.' },
  { text: 'There\'s only one thing I hate more than lying: skim milk. Which is water that\'s lying about being milk.' },
  { text: 'The less I know about other people\'s affairs, the happier I am. I\'m not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.' },
  { text: 'When I eat, it is the food that is scared.' },
  { text: 'My only official recommendations are US Army-issued mustache trimmers, Morton\'s Salt, and the C.R. Lawrence Fein two inch axe-style scraper oscillating knife blade.' },
  { text: 'It\'s always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain.' },
  { text: 'There are three acceptable haircuts: high and tight, crew cut, buzz cut.' },
  { text: 'Capitalism: God\'s way of determining who is smart and who is poor.' },
  { text: 'Any dog under fifty pounds is a cat and cats are useless.' },
  { text: 'Fish, for sport only, not for meat. Fish meat is practically a vegetable.' },
  { text: 'There is only one bad word: taxes.' },
  { text: 'Give a man a fish and feed him for a day. Don\'t teach a man to fish… and feed yourself. He\'s a grown man. And fishing\'s not that hard.' },
  { text: 'Great job, everyone. The reception will be held in each of our individual houses, alone.' },
  { text: 'There are only three ways to motivate people: money, fear, and hunger.' },
  { text: 'Friends: one to three is sufficient.' },
  { text: 'Breakfast food can serve many purposes.' },
  { text: 'Honor: if you need it defined, you don\'t have it.' },
  { text: 'I like saying ‘No,’ it lowers their enthusiasm.' },
  { text: 'You had me at meat tornado.' },
  { text: 'There must be a mistake, you\'ve accidentally given me the food that my food eats.' },
  { text: 'Keep your tears in your eyes where they belong.' },
  { text: 'I\'ve cried twice in my life. Once when I was seven and hit by a school bus. And then again when I heard that Li\'l Sebastian has passed.' },
  { text: 'I hate everything.' },
  { text: 'I love nothing.' },
  { text: 'I love riddles!' },
  { text: 'Don\'t waste energy moving unless necessary.' },
  { text: 'I\'ll take that steak to go. Please and thank you.' },
  { text: 'Creativity is for people with glasses who like to lie.' },
  { text: 'Children are terrible artists and artists are crooks.' },
  { text: 'Tom put all my records into this rectangle!' },
  { text: 'I believe luck is a concept invented by the weak to explain their failures.' },
  { text: 'What\'s cholesterol?' },
  { text: 'People who buy things are suckers.' },
  { text: 'I\'m going to get 12 eggs and part of a dead animal. Dealer\'s choice. Please and thank you.' },
  { text: 'I wanna punch you in the face so bad right now.' },
]

module.exports = { quotes }
